version: '3.8'

services:
  api:
    build: .
    container_name: api-movie-review
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=movie_review
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-movie-review
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_review
